server:
  port: 8093

spring:
  application:
    name: FlightViewModel
  config:
    import: optional:configserver:http://localhost:8888
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411/
#  sleuth:
#    enabled: true
#    sampler:
#      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
