server:
  port: 8001

spring:
  application:
    name: FlightRTDIS
  config:
    import: optional:configserver:http://localhost:8888
  data:
    elasticsearch:
      cluster-name: my-elasticsearch-cluster
      cluster-nodes: localhost:9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Logging Configuration
logging:
  level:
    root: INFO
