spring:
  application:
    name: FlightDomainModel
  cloud:
    config:
      url: http://localhost:8888
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  kafka:
    consumer:
      topic: rtds_flight
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      topics:
        arrival: ds_departure
        departure: ds_arrival
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
