spring:
  application:
    name: FlightViewModel
  cloud:
    config:
      url: http://localhost:8888
  kafka:
    consumer:
      topics:
        departure: ds_departure
        arrival: ds_arrival
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          deserializer:
            key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: localhost:9092
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: flightDB
