externalApi:
  baseUrl: http://api.aviationstack.com
  accessKey: 4a18359744e6bae6aa7953abb1db928f

# Kafka Producer Configuration
spring:
  kafka:
    producer:
      topic: rtds_flight
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
