spring:
  application:
    name: FlightDomainModel
  cloud:
    config:
      url: http://localhost:8888
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  kafka:
    consumer:
      topic: rtds_flight
      key-serializer: org.apache.kafka.common.serialization.StringDeSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      spring.json.trusted.packages: "*"

