opensky:
  base-url: https://opensky-network.org

# Kafka Producer Configuration
spring:
  kafka:
    producer:
      topic: rtds_flight
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
